/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubmissionService } from "../submission.service";
import { SubmissionCreateInput } from "./SubmissionCreateInput";
import { Submission } from "./Submission";
import { SubmissionFindManyArgs } from "./SubmissionFindManyArgs";
import { SubmissionWhereUniqueInput } from "./SubmissionWhereUniqueInput";
import { SubmissionUpdateInput } from "./SubmissionUpdateInput";
import { ResultFindManyArgs } from "../../result/base/ResultFindManyArgs";
import { Result } from "../../result/base/Result";
import { ResultWhereUniqueInput } from "../../result/base/ResultWhereUniqueInput";

export class SubmissionControllerBase {
  constructor(protected readonly service: SubmissionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Submission })
  async createSubmission(
    @common.Body() data: SubmissionCreateInput
  ): Promise<Submission> {
    return await this.service.createSubmission({
      data: {
        ...data,

        language: data.language
          ? {
              connect: data.language,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        code: true,
        createdAt: true,
        id: true,
        input: true,

        language: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Submission] })
  @ApiNestedQuery(SubmissionFindManyArgs)
  async submissions(@common.Req() request: Request): Promise<Submission[]> {
    const args = plainToClass(SubmissionFindManyArgs, request.query);
    return this.service.submissions({
      ...args,
      select: {
        code: true,
        createdAt: true,
        id: true,
        input: true,

        language: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async submission(
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Submission | null> {
    const result = await this.service.submission({
      where: params,
      select: {
        code: true,
        createdAt: true,
        id: true,
        input: true,

        language: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubmission(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() data: SubmissionUpdateInput
  ): Promise<Submission | null> {
    try {
      return await this.service.updateSubmission({
        where: params,
        data: {
          ...data,

          language: data.language
            ? {
                connect: data.language,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          code: true,
          createdAt: true,
          id: true,
          input: true,

          language: {
            select: {
              id: true,
            },
          },

          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubmission(
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Submission | null> {
    try {
      return await this.service.deleteSubmission({
        where: params,
        select: {
          code: true,
          createdAt: true,
          id: true,
          input: true,

          language: {
            select: {
              id: true,
            },
          },

          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/results")
  @ApiNestedQuery(ResultFindManyArgs)
  async findResults(
    @common.Req() request: Request,
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Result[]> {
    const query = plainToClass(ResultFindManyArgs, request.query);
    const results = await this.service.findResults(params.id, {
      ...query,
      select: {
        createdAt: true,
        errorField: true,
        executionTime: true,
        id: true,
        output: true,

        submission: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/results")
  async connectResults(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        connect: body,
      },
    };
    await this.service.updateSubmission({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/results")
  async updateResults(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        set: body,
      },
    };
    await this.service.updateSubmission({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/results")
  async disconnectResults(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() body: ResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      results: {
        disconnect: body,
      },
    };
    await this.service.updateSubmission({
      where: params,
      data,
      select: { id: true },
    });
  }
}
